### ISSUE TITLE
Not working anymore :(

### ISSUE THREAD

**Issue by okdas** [gierschv/node-hubic-swiftauth#1]
[Error][X-Auth-User = email@domain.tld] This application version is deprecated. Please download the latest version: https://hubic.com/en/downloads

**Comment by gierschv** [comment]
Hi,
Thank you for the feedback, I'm aware of this issue.
I'll work on an update using the new OAuth API when I'll have some free time.

Vincent

**Comment by gierschv** [comment]
Done.
