### ISSUE TITLE
port question

### ISSUE THREAD

**Issue by szepeviktor** [gierschv/node-hubic-swiftauth#2]
Thank you for this script.

If you listen on port 8080
how will I access https://....?

Who will serve https??

**Comment by szepeviktor** [comment]
Ah!
node-hubic-swiftauth provides only authentication, NO file transfer
Do I understand correctly?

**Comment by szepeviktor** [comment]
I'd like to upload files to hubiC from my linux server.

**Comment by gierschv** [comment]
Sure, It provides an OpenStack auth v1-like API: the module fetches a swift token from the hubiC API and returns it to your swift client.
I don't use it directly as a HTTPS server, but as a HTTP server with a HTTPS reverse proxy in front (e.g. nginx).

**Comment by szepeviktor** [comment]
So to run it I need to set up nginx.
Could you please state it in the docs?

**Comment by gierschv** [comment]
Or you can do something like that: https://github.com/gierschv/node-hubic-swiftauth/blob/a4a4e27968a973450822bddfbfeb77e137b0f3a0/hubic-swiftauth.js#L79
I removed it in the new version since it's not really the goal of the module.

**Comment by szepeviktor** [comment]
Thank you very much!
It is very useful to have a build-int https server (the "s" is missing in the code)
`srv = http.createServer(options, httpListener);`
I've come to know that the hubiC container name is `default`
Please add it to the docs.

**Comment by gierschv** [comment]
There was not really a [mistake](https://github.com/gierschv/node-hubic-swiftauth/blob/a4a4e27968a973450822bddfbfeb77e137b0f3a0/hubic-swiftauth.js#L4).
And "default" is always the default container in swift. Btw hubiC creates some other containers for the backup feature.

**Comment by szepeviktor** [comment]
Oh! Thank you. I know nothing about swift.
I am looking for a reliable website backup solution.

**Comment by gierschv** [comment]
I think that you should try the [Public Cloud Archive](http://www.ovh.ie/cloud/archive/) by OVH (Amazon Glacier-like), it's designed to be write-only by FTP/SFTP/RSYNC/SCP, really easy to use to backup some stuff from a linux box.

**Comment by szepeviktor** [comment]
It is very nice from you. Amazon Glacier is also very-very cheap.
